# Texto (str)
# Númerico (int, float, complex)
# Sequência (list, tuple, range) 
# Mapa (dict)
# Colecão (set, frozenset)
# Booleano (bool)
# Binário (bytes, bytearray, memoryview)

print(1 + 19)
print(1.5 + 1 + 0.5)
print(True)
print(False)
print("Danillo")
